Port = 10000
DownloadPath = "/app/podsync"
MaxParallelDownloads = 2

[Storage]
Type = "local"
DataDir = "/app/data"   # <-- MUSI być tutaj (root)

[Feeds.feed1]
URL = "https://www.youtube.com/channel/UCO6_hwMtQZ0SLElfDMaqJGQ"
